VALID_PHRASES = [
    "padang pariaman",
    "kab padang pariaman",
    "kota pariaman",
    "pariaman",
]

INVALID_PHRASES = [

    # PADANG
    "lubuk begalung",
    "lubuk kilangan",
    "bandar buat",
    "kuranji",
    "ampang",
    "pauh",
    "parak",
    "andalas",
    "pangilun",
    "purus",
    "indarung",
    "kalawi",
    "gadut",
    "by pass",
    "pasar baru",
    "muhammad hatta",
    "m hatta",
    "simpang piai",
    "sutomo",
    "anduring",
    "ratulangi",
    "sawahan",
    "taruko",

    # SUMBAR NON PARIAMAN
    "bukittinggi",
    "payakumbuh",
    "solok",
    "agam",
    "dharmasraya",
    "pasaman",
    "sijunjung",
    "sawah lunto",
    "tanah datar",
    "pesisir selatan",
    "lima puluh kota",

    # NATIONAL
    "jakarta",
    "bekasi",
    "tangerang",
    "bogor",
    "bandung",
    "surabaya",
    "depok",
    "malang",
    "tasikmalaya",
    "medan",
    "makassar",
    "lampung",
    "semarang",
    "palembang",
    "pekanbaru",
    "denpasar",
    "sleman",
    "pasuruan",
    "cimahi",
    "banjarmasin",
    "balikpapan",
    "gresik",
    "sukabumi",
    "tegal",
    "pontianak",
]